name: CI

on:
  pull_request:
  push:
    branches: ["main"]
    paths-ignore:
      - 'data/generated/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-ci

jobs:
  redirect:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - run: bash tests/redirect.sh
          shell: bash
        - name: Generate with _just
          uses: ./
          with:
            path: test
  compress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: bash tests/compress.sh
        shell: bash
      - name: Compress with _just
        uses: ./
        with:
          path: test
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: bash tests/docs.sh
        shell: bash
      - name: Generate with _just
        uses: ./
        with:
          path: test