name: Update "latest" repo

on:
  push:
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: bash src/latest.sh
        shell: bash
        env:
          GITHUB_ACTION_PATH: 
      - uses: actions/setup-node@v4
      - name: Commit to js-just/latest
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "latest"
          destination-github-username: js-just
          destination-repository-name: latest
          user-email: "support@juststudio.is-a.dev"
          target-branch: main
      - name: Update latest ID
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "latest"
          destination-github-username: js-just
          destination-repository-name: raw-api
          user-email: "support@juststudio.is-a.dev"
          target-branch: main
          target-directory: "v1/latest"
          commit-message: "Update latest version"
      
