name: Website

on:
  push:
    branches: ["main"]
    paths:
    - "website/**"
    - ".github/workflows/publish.yml"
    - "just.config.js"
    - "CNAME"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove test pages
        run: rm -f -v website/test.md && rm -f -v website/mattcone.md && rm -f -v website/langs.md && rm -f -v website/test.justc && bash "website/prepare.sh" && rm -f -v "website/prepare.sh"
        shell: bash
      - name: Generate with _just
        uses: js-just/latest@main
        with:
          path: website
      - name: Commit to js-just/website
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "website"
          destination-github-username: js-just
          destination-repository-name: website
          user-email: "support@juststudio.is-a.dev"
          target-branch: main
          target-directory: "main"
