name: Test website

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-test-website
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: rm -f "website/index.html" && cp "website/test.md" "website/index.md" && rm -f "website/test.md" && rm -f "just.config.js" && cp "tests/just.config.js" "just.config.js"
        shell: bash
      - name: Generate with _just
        uses: js-just/_just@main
        with:
          path: website
      - name: CNAME
        run: echo "test.just.is-a.dev" > "website/CNAME"
        shell: bash
      - uses: actions/setup-node@v4
      - name: Commit
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "website"
          destination-github-username: js-just
          destination-repository-name: test
          user-email: "support@juststudio.is-a.dev"
          target-branch: main
      
