name: Test website & Raw API

on:
  push:
    branches: [main]
    paths-ignore:
      - 'data/generated/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-test-website-and-raw-api
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: rm -f "website/index.html" && cp "website/test.md" "website/index.md" && rm -f "website/test.md" && rm -f "just.config.js" && cp "tests/just.config.js" "just.config.js" && echo "test" > "website/noheadertest.md" && cp "website/test.justc" "website/index.justc" && rm -f "website/test.justc" && bash "website/prepare.sh" && rm -f -v "website/prepare.sh"
        shell: bash
      - uses: actions/setup-node@v4
      - name: Make syntax highlighting test markdown file
        run: node tests/syntaxhighlighting.js
      - name: Generate with _just
        uses: js-just/_just@main
        with:
          path: website
      - name: CNAME and LICENSE
        run: echo "test.just.is-a.dev" > "website/CNAME" && cp "LICENSE" "website/LICENSE"
        shell: bash
      - uses: actions/setup-node@v4
      - name: Commit
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "website"
          destination-github-username: js-just
          destination-repository-name: test
          user-email: "support@juststudio.is-a.dev"
          target-branch: main
  raw-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get
        run: bash "src/last-commit.sh"
        shell: bash
      - name: Set
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "_lastcommit"
          destination-github-username: js-just
          destination-repository-name: raw-api
          user-email: "support@juststudio.is-a.dev"
          target-branch: main
          target-directory: "v1/last-commit"
          commit-message: "Update last commit value"
  current-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get
        run: bash "src/current-commit.sh"
        shell: bash
      - name: Set
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "_lastcommit"
          destination-github-username: js-just
          destination-repository-name: _just
          user-email: "support@juststudio.is-a.dev"
          target-branch: main
          target-directory: "data/generated"
          commit-message: "Update current commit value"
      
